/*
 * Readme.h
 */
const unsigned char WebSide[] = {
"<!DOCTYPE html PUBLIC \"-//WAPFORUM//DTD XHTML Mobile 1.0//EN\" \"http://www.wapforum.org/DTD/xhtml-mobile10.dtd\">\r\n"
"<html xmlns=\"http://www.w3.org/1999/xhtml\"><head>\r\n"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
"<meta http-equiv=\"refresh\" content=\"5\" />\r\n"
"<title>Real Time Data Window</title>\r\n"
"<style type=\"text/css\">\r\n"
"table {\r\n"
"	font-size:0.8em;\r\n"
"	font-family:Georgia,\"Gill Sans MT\", \"Gill sans\", \"Trebuchet ms\", sans-serif;\r\n"
"	line-height:1.4em;\r\n"
"	color: #5B0006;\r\n"
"	background-color:#FFEDEF;\r\n"
"	width:100%;\r\n"
"	border-collapse:collapse;\r\n"
"}\r\n"
"caption{\r\n"
"	color:#F8EFF0;\r\n"
"	background-color:inherit;\r\n"
"	font-size:25px;\r\n"
"	background-image:url(poetryforbrowser/caption.jpg);\r\n"
"	background-repeat:repeat-x;\r\n"
"	background-position:0 0;\r\n"
"	padding:28px 10px 7px 5px;\r\n"
"	text-align:right;\r\n"
"}\r\n"
"tfoot th,\r\n"
"tfoot td {\r\n"
"	color:#F8EFF0;\r\n"
"	background-color:inherit;\r\n"
"	font-size:25px;\r\n"
"	background-image:url(poetryforbrowser/tfoot.jpg);\r\n"
"	background-repeat:repeat-x;\r\n"
"	background-position:0 -2px;\r\n"
"}\r\n"
"tfoot{text-align:right;}\r\n"
"tfoot td{padding:7px 10px 28px 5px;}\r\n"
"tfoot th{padding:7px 2px 28px 2px;}\r\n"
"thead th,\r\n"
"tbody th {\r\n"
"	background-color:#FAE5E7;\r\n"
"	color: #5B0006;\r\n"
"	padding:7px;\r\n"
"	text-align:left;\r\n"
"}\r\n"
"tbody tr:hover,\r\n"
"tbody tr th:hover{\r\n"
"    background-color:#FDF9F9;\r\n"
"    color:#000;\r\n"
"}\r\n"
"td{padding:7px;}\r\n"
"thead th{border-bottom:1px dotted  #908F8B;}\r\n"
"thead th:first-child{border:none;}\r\n"
"tbody th{border-right:1px dotted #908F8B;}\r\n"
"table a {\r\n"
"	width:100%;\r\n"
"	display:block;\r\n"
"	color: #5B0006;\r\n"
"	background-color:inherit;\r\n"
"	line-height:1.5em;\r\n"
"}\r\n"
"table a:visited {\r\n"
"	color: #908F8B;\r\n"
"	background-color:inherit;\r\n"
"}\r\n"
"tbody td+td+td+td a:before{\r\n"
"	 content:\"\21D3\";\r\n"
"	 text-align:right;\r\n"
"}\r\n"
"table a:hover {\r\n"
"	color: #C9020F;\r\n"
"	background-color:inherit;\r\n"
"}\r\n"
"</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<table><thead><th>REal Time Data Window</th></thead>\r\n"
"<tbody><tr><td><p align=\"justify\"><h2>Beta Test</h2></p></td></tr>\r\n"
"<tr><td><strong>Sensor Object</strong></td><td><strong>Value</strong></td></tr>\r\n"
"<tr><td>Sensor 1</td><td>AD%1  \r\n"
"</td></tr>\r\n"
"<tr><td>Sensor 2</td><td>AD%2  \r\n"
"</td></tr>\r\n"
"<tr><td>Sensor 3</td><td>AD%3  \r\n"
"</td></tr>\r\n"
"</tbody>\r\n"
"<tfoot><p align=\"justify\">Sidhdharth Kaul & Nandan Mehta<br />siddharth.kaul.k10@gmail.com & nandan.ee20@iite.edu.in<br /></p>\r\n"
"</tfoot></table>\r\n"
"</body></html>\r\n"
};
/*
"<tr><td>Sensor 4</td><td>AD%4  \r\n"
"</td></tr>\r\n"
"<tr><td>Sensor 5</td><td>AD%5  \r\n"
"</td></tr>\r\n"
"<tr><td>Sensor 6</td><td>AD%6  \r\n"
"</td></tr>\r\n"
*/