/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.16                          *
*        Compiled Jun  4 2012, 15:48:59                              *
*        (c) 2011 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "GUI.h"
#include "PROGBAR.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
static PROGBAR_Handle ahProgBar[2];
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x01)
#define ID_LISTBOX_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_TEXT_0    (GUI_ID_USER + 0x04)
#define ID_TEXT_1    (GUI_ID_USER + 0x05)
#define ID_TEXT_2    (GUI_ID_USER + 0x06)
#define ID_TEXT_3    (GUI_ID_USER + 0x07)
#define ID_PROGBAR_0    (GUI_ID_USER + 0x08)
#define ID_TEXT_4    (GUI_ID_USER + 0x09)
#define ID_PROGBAR_1    (GUI_ID_USER + 0x0A)
#define ID_TEXT_5    (GUI_ID_USER + 0x0B)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 320, 240, 0, 0 },
  { BUTTON_CreateIndirect, "Graph", ID_BUTTON_0, 227, 7, 80, 60, 0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 129, 6, 80, 221, 0, 0 },
  { BUTTON_CreateIndirect, "Control", ID_BUTTON_1, 228, 78, 80, 60, 0, 0 },
  { TEXT_CreateIndirect, "Created By", ID_TEXT_0, 231, 145, 74, 17, 0, 0 },
  { TEXT_CreateIndirect, "Siddharth Kaul", ID_TEXT_1, 231, 163, 80, 20, 0, 0 },
  { TEXT_CreateIndirect, "Nandan Mehta", ID_TEXT_2, 231, 178, 80, 20, 0, 0 },
  { TEXT_CreateIndirect, "192.168.1.11", ID_TEXT_3, 231, 196, 80, 20, 0, 0 },
  { PROGBAR_CreateIndirect, "Temperature 1", ID_PROGBAR_0, 12, 8, 20, 169, 1, 0 },
  { TEXT_CreateIndirect, "Sensor1", ID_TEXT_4, 7, 186, 43, 20, 0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_1, 72, 8, 20, 169, 1, 0 },
  { TEXT_CreateIndirect, "Sensor2", ID_TEXT_5, 61, 187, 40, 20, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
unsigned int adcfinalvalue;
void assignfinalvalue(unsigned int value)
{
	adcfinalvalue = value;
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int Id, NCode;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_AddString(hItem, "Item 0");
    LISTBOX_AddString(hItem, "Item 1");
    LISTBOX_AddString(hItem, "Item 2");
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
		ahProgBar[0] = hItem;
		PROGBAR_EnableMemdev(hItem);
		PROGBAR_SetMinMax(hItem, 0, 100);
		PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
		PROGBAR_SetValue(hItem, adcfinalvalue);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Graph'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Control'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
		PROGBAR_SetBarColor(hItem, 0, GUI_GREEN);
		PROGBAR_SetValue(hItem, adcfinalvalue);
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
//extern int realtime(void);
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), &_cbDialog, WM_HBKWIN, 0, 0);
	//GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	
	return hWin;
}
void updateProg()
{
		PROGBAR_SetBarColor(ahProgBar[0], 0, GUI_GREEN);
		PROGBAR_SetValue(ahProgBar[0], adcfinalvalue);
}
// USER START (Optionally insert additional public code)
// USER END
/*
 * Watchdog
 */


/*************************** End of file ****************************/
